api_platform:
    title: AGP-PACT CORE API
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        multipart: ['multipart/form-data']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    collection:
        pagination:
            enabled_parameter_name: pagination
            items_per_page_parameter_name: itemsPerPage
    exception_to_status:
        App\Exception\InvalidActionInputException: 400
        App\Exception\UnavailableDataException: 404
        App\Exception\UserCreationException: 400
        App\Exception\ComplainantCreationException: 400
        pp\Exception\UnauthorizedActionException: 403
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        pagination_enabled: false
    use_symfony_listeners: true
