vich_uploader:
    db_driver: orm

    mappings:
        attached_files:
            uri_prefix: /uploads/files/attached_files
            upload_destination: '%kernel.project_dir%/public/uploads/files/attached_files'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_remove: true
            delete_on_update: true
